### ISSUE TITLE
ERR unknown command `FT.CREATE`

### ISSUE THREAD

**Issue by giangcoi48k** [redis/redis-om-dotnet#106]
I followed exactly step by step on the document
- add package Redis.OM
- run docker: docker run -p 6379:6379 -p 8001:8001 redis/redis-stack

But in this step: 
```
var provider = new RedisConnectionProvider("redis://localhost:6379");
provider.Connection.CreateIndex(typeof(Customer));
```
I got this error:

> StackExchange.Redis.RedisServerException: ERR unknown command `FT.CREATE`, with args beginning with: `customer-idx`, `ON`, `Json`, `PREFIX`, `1`, `FiinX.MiscellaneousTestApi.Controllers.Customer:`, `SCHEMA`, `$.FirstName`, `AS`, 
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2834
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 53
   at StackExchange.Redis.RedisDatabase.Execute(String command, ICollection`1 args, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1226
   at StackExchange.Redis.RedisDatabase.Execute(String command, Object[] args) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1222
   at Redis.OM.RedisConnection.Execute(String command, String[] args)
   at Redis.OM.RediSearchCommands.CreateIndex(IRedisConnection connection, Type type)
   at FiinX.MiscellaneousTestApi.Controllers.WeatherForecastController.Get() in D:\giang.ho\Workspace\FiinX\test\FiinX.MiscellaneousTestApi\Controllers\WeatherForecastController.cs:line 23
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

How can I resolve this issue? I am a newbie in RedisOM

**Comment by slorello89** [comment]
Hi @giangcoi48k - That's really odd, 

`ERR unknown command FT.CREATE,` 

This indicates to me that redis-stack did not correctly load RediSearch

can you open the redis-cli and run: `MODULE LIST` and let me know what that prints for you?

**Comment by giangcoi48k** [comment]
hi @slorello89 
![image](https://user-images.githubusercontent.com/12107588/168730875-612ed574-4081-4bac-a941-c465dc7f456f.png)
