### ISSUE TITLE
Support StackExchange.Redis connection string

### ISSUE THREAD

**Issue by Misiu** [redis/redis-om-dotnet#137]
Hi there,
I'm new to this project, so this might be something that is already possible.

I'm currently using https://github.com/thepirat000/CachingFramework.Redis to add cache support to my API (I needed tags, which aren't officially supported (yet)).
I'm using connection sting in this format: `localhost:6379,abortConnect=false,ssl=false,allowAdmin=true`, but as soon as I try to use it with RedisOM I get this error:

```
StackExchange.Redis.RedisCommandException
  HResult=0x80131500
  Message=The database does not exist on the server: 6379
  Source=StackExchange.Redis
  StackTrace:
   at StackExchange.Redis.ConnectionMultiplexer.PrepareToPushMessageToBridge[T](Message message, ResultProcessor`1 processor, IResultBox`1 resultBox, ServerEndPoint& server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2233
   at StackExchange.Redis.ConnectionMultiplexer.TryPushMessageToBridgeAsync[T](Message message, ResultProcessor`1 processor, IResultBox`1 resultBox, ServerEndPoint& server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2236
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object state, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2737
   at StackExchange.Redis.RedisBase.ExecuteAsync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 46
   at Redis.OM.RedisConnection.<ExecuteAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RedisOMTest.HostedServices.IndexCreationService.<StartAsync>d__2.MoveNext() in C:\Users\tomasz.j\source\repos\RedisOMTest\RedisOMTest\HostedServices\IndexCreationService.cs:line 19
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
   at RedisOMTest.Program.Main(String[] args) in C:\Users\tomasz.j\source\repos\RedisOMTest\RedisOMTest\Program.cs:line 39
  This exception was originally thrown at this call stack:
    StackExchange.Redis.ConnectionMultiplexer.PrepareToPushMessageToBridge<T>(StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor<T>, StackExchange.Redis.IResultBox<T>, ref StackExchange.Redis.ServerEndPoint) in ConnectionMultiplexer.cs
    StackExchange.Redis.ConnectionMultiplexer.TryPushMessageToBridgeAsync<T>(StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor<T>, StackExchange.Redis.IResultBox<T>, ref StackExchange.Redis.ServerEndPoint) in ConnectionMultiplexer.cs
    StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl<T>(StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor<T>, object, StackExchange.Redis.ServerEndPoint) in ConnectionMultiplexer.cs
    StackExchange.Redis.RedisBase.ExecuteAsync<T>(StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor<T>, StackExchange.Redis.ServerEndPoint) in RedisBase.cs
    Redis.OM.RedisConnection.ExecuteAsync(string, string[])
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
    RedisOMTest.HostedServices.IndexCreationService.StartAsync(System.Threading.CancellationToken) in IndexCreationService.cs
```

the line that is causing this error is:
```
public async Task StartAsync(CancellationToken cancellationToken)
{
    var info = (await _provider.Connection.ExecuteAsync("FT._LIST")).ToArray().Select(x => x.ToString()); // <- this line cause the problem.
    if (info.All(x => x != "customer-idx"))
    {
        await _provider.Connection.CreateIndexAsync(typeof(Customer));
    }
}
```

Port number from connection string is threaded as database number:
`redis://localhost:6379` - this works
`localhost:6379,abortConnect=false,ssl=false,allowAdmin=true` - this doesn't

**Comment by Misiu** [comment]
@slorello89 thank you for such a fast reply.
As it turns out I can pass ConnectionMultiplexer to https://github.com/thepirat000/CachingFramework.Redis and to Redis OM.
Really looking forward to using this library 💪
