### ISSUE TITLE
0.2.2 breaking changes from 0.2.1

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#201]
Hi @slorello89,  I started playing with 0,2,2 and find it breaking from 0.2.1.  Particularity the following types of errors.  I'm going to follow up with some more testing as time permits.

```csharp
errorCode: "RedisServerException"
errors: []
message: "Syntax error at offset 11 near LL1DB0LCCU"
stackTrace: "[ListMailboxRequest: 9/16/2022 7:37:24 AM]:\n[REQUEST: {}]
StackExchange.Redis.RedisServerException: Syntax error at offset 11 near LL1DB0LCCU
   at Redis.OM.RedisConnection.ExecuteAsync(String command, String[] args)
   at Redis.OM.RediSearchCommands.SearchAsync[T](IRedisConnection connection, RedisQuery query)
   at Redis.OM.Searching.RedisCollection`1.FirstOrDefaultAsync(Expression`1 expression)
  ...
```

Update: I've been seeing some weird issues after this latest rider update.  The same offending code seems to run fine in my linqpad.  I'll update to see if I can narrow down where this issue is coming from.

Update: Here is the offending code:
```csharp
var working = await RedisDb.MailboxRecord
  .FirstOrDefaultAsync(x => x.Owners.Contains("LL1DB0LCCU"))
  .ConfigureAwait(false);
```
which correctly produces
```
"FT.SEARCH" "mailboxrecord-idx" "(@Owners:{LL1DB0LCCU})" "LIMIT" "0" "1"
```
and 
```csharp
var customerRecord = new CustomerRecord { Code = "LL1DB0LCCU" };
var broken = await RedisDb.MailboxRecord
  .FirstOrDefaultAsync(x => x.Owners.Contains(customerRecord.Code))
  .ConfigureAwait(false);
```
which produces
```
"FT.SEARCH" "mailboxrecord-idx" "(LL1DB0LCCU:{\\@Owners})" "LIMIT" "0" "1"
```

I can work around it by doing this, or reverting back to 0.2.1
```csharp
await redisDb.MailboxRecord.FirstOrDefaultAsync(x => x.Owners.Contains($"{customerRecord.Code}")).ConfigureAwait(false)
```

@slorello89  Can we push a quick hot-fix for this ASAP?

**Comment by VagyokC4** [comment]
@slorello89 Can we get a 0.2.3 release real quick?

**Comment by slorello89** [comment]
Just pushed 0.2.3
