### ISSUE TITLE
When using a large Or operator, Syntax error  is thrown...

### ISSUE THREAD

**Issue by zulander1** [redis/redis-om-dotnet#275]
I have an issue when query with a large Or (like 100 or conditions) operator I get a syntax error, I am not sure if this RedisSearch or Redis-OM, i've changed the limit to 200 I am using ExpressionVisitor to convert "Contain":

```
var provider = new RedisConnectionProvider("redis://localhost:6379");
var connection = provider.Connection;
var customers = provider.RedisCollection<Customer>();
var customerAggregations = provider.AggregationSet<Customer>();

// Create index
connection.CreateIndex(typeof(Customer));

// Get Index info
var indexinfo = connection.GetIndexInfo(typeof(Customer));

// Insert Object
var listOfCustomers = Enumerable.Range(1, 100).Select(x => new Customer() { Id = Guid.NewGuid(), LastName = x.ToString() });
foreach (var item in listOfCustomers)
{
    await customers.InsertAsync(item);
}

var ids = listOfCustomers.Select(x => x.Id).Take(100).ToArray();

Expression<Func<Customer, bool>> expression = x => ids.Contains(x.Id);
RedisQueryVisitor redisQueryVisitor = new();
var visited = (Expression<Func<Customer, bool>>)redisQueryVisitor.Visit(expression);

var list = customers.Where(visited).Take(200).ToList();

Console.ReadLine();

[Document(StorageType = StorageType.Json)]
public class Customer
{
    [Indexed][RedisIdField] public Guid Id { get; set; }
    [Indexed] public string LastName { get; set; }
}

public class RedisQueryVisitor : ExpressionVisitor
{
    protected override Expression VisitMethodCall(MethodCallExpression node)
    {
        if (node.Method.Name == "Contains" && node.Arguments.Count == 2)
        {
            var right = (MemberExpression)node.Arguments[1];
            var left = (MemberExpression)node.Arguments[0];

            if (left.Member.MemberType == MemberTypes.Property)
            {
                PropertyInfo leftPI = (PropertyInfo)left.Member;

                //Check if the secound parameter is collection
                if (leftPI.PropertyType.IsArray)
                    return base.VisitMethodCall(node);
            }

            #region Get List

            var list = (IEnumerable)Expression.Lambda<Func<object>>(node.Arguments[0]).Compile()();

            var castedOBject = list.OfType<object>().ToList();

            #endregion Get List

            if (castedOBject.Any())
                return castedOBject.Select(x => Expression.Equal(Expression.Property(right.Expression, right.Member.Name), Expression.Constant(x))).Aggregate((a, x) => a == null ? x : Expression.OrElse(a, x));
        }

        return base.VisitMethodCall(node);
    }
}
```

**Comment by slorello89** [comment]
@zulander1 - I don't suppose you can share the error you're getting?

**Comment by zulander1** [comment]
@slorello89, had to anonymize some path and name, but there you go

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Exception: Syntax error at offset 1100 near e4865202\-d377\-ed11\-811f\-005056a6c176
      Failed on FT.SEARCH A:B:Recipient:idx ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((@Id:{d41bf428\-45d0\-ec11\-8105\-005056a63161}) | (@Id:{562af428\-45d0\-ec11\-8105\-005056a63161})) | (@Id:{13931c81\-5976\-ed11\-811f\-005056a6c176})) | (@Id:{e4f597b8\-5b76\-ed11\-811f\-005056a6c176})) | (@Id:{a016d959\-5d76\-ed11\-811f\-005056a6c176})) | (@Id:{63f24364\-6576\-ed11\-811f\-005056a6c176})) | (@Id:{71251b92\-6576\-ed11\-811f\-005056a6c176})) | (@Id:{680bc0d9\-7076\-ed11\-811f\-005056a6c176})) | (@Id:{f97a259a\-fa76\-ed11\-811f\-005056a6c176})) | (@Id:{fbe5f8e4\-fc76\-ed11\-811f\-005056a6c176})) | (@Id:{714a394b\-0077\-ed11\-811f\-005056a6c176})) | (@Id:{e3c9285b\-0477\-ed11\-811f\-005056a6c176})) | (@Id:{4f30258b\-0577\-ed11\-811f\-005056a6c176})) | (@Id:{7b3c5982\-0a77\-ed11\-811f\-005056a6c176})) | (@Id:{d53ec993\-0f77\-ed11\-811f\-005056a6c176})) | (@Id:{63da5dfe\-1877\-ed11\-811f\-005056a6c176})) | (@Id:{ec6f556b\-cc77\-ed11\-811f\-005056a6c176})) | (@Id:{c59b67a7\-d277\-ed11\-811f\-005056a6c176})) | (@Id:{e4865202\-d377\-ed11\-811f\-005056a6c176})) | (@Id:{611afb7f\-d577\-ed11\-811f\-005056a6c176})) | (@Id:{9bd5e586\-d777\-ed11\-811f\-005056a6c176})) | (@Id:{8b2da13a\-d977\-ed11\-811f\-005056a6c176})) | (@Id:{50a78ca9\-db77\-ed11\-811f\-005056a6c176})) | (@Id:{50bb8390\-df77\-ed11\-811f\-005056a6c176})) | (@Id:{4b7ce989\-e077\-ed11\-811f\-005056a6c176})) | (@Id:{68f348a0\-e177\-ed11\-811f\-005056a6c176})) | (@Id:{d2bd1292\-e477\-ed11\-811f\-005056a6c176})) | (@Id:{509e9fb9\-e877\-ed11\-811f\-005056a6c176})) | (@Id:{11c5e70d\-eb77\-ed11\-811f\-005056a6c176})) | (@Id:{95494231\-ee77\-ed11\-811f\-005056a6c176})) | (@Id:{a5d1b3bc\-f877\-ed11\-811f\-005056a6c176})) | (@Id:{f069b2fa\-fa77\-ed11\-811f\-005056a6c176})) | (@Id:{9e53dd5c\-fe77\-ed11\-811f\-005056a6c176})) | (@Id:{f5a4ead8\-ff77\-ed11\-811f\-005056a6c176})) | (@Id:{4abb8490\-0278\-ed11\-811f\-005056a6c176})) | (@Id:{979cf701\-0778\-ed11\-811f\-005056a6c176})) | (@Id:{6d122765\-e978\-ed11\-811f\-005056a6c176})) | (@Id:{f29b885e\-5a79\-ed11\-811f\-005056a6c176})) | (@Id:{6006ce12\-5c79\-ed11\-811f\-005056a6c176})) | (@Id:{a6f76a22\-6079\-ed11\-811f\-005056a6c176})) | (@Id:{26e8227b\-6279\-ed11\-811f\-005056a6c176})) | (@Id:{acf15311\-6379\-ed11\-811f\-005056a6c176})) | (@Id:{081c5d39\-6379\-ed11\-811f\-005056a6c176})) | (@Id:{9a17bfa6\-6579\-ed11\-811f\-005056a6c176})) | (@Id:{692fac5c\-6679\-ed11\-811f\-005056a6c176})) | (@Id:{a2e052e6\-6779\-ed11\-811f\-005056a6c176})) | (@Id:{009db37f\-7979\-ed11\-811f\-005056a6c176})) | (@Id:{26cd280a\-7a79\-ed11\-811f\-005056a6c176})) | (@Id:{198bf085\-7a79\-ed11\-811f\-005056a6c176})) | (@Id:{5426de62\-7d79\-ed11\-811f\-005056a6c176})) | (@Id:{d550a297\-7e79\-ed11\-811f\-005056a6c176})) | (@Id:{4367b81e\-7c79\-ed11\-811f\-005056a6c176})) | (@Id:{e931656b\-8779\-ed11\-811f\-005056a6c176})) | (@Id:{ce37da30\-8979\-ed11\-811f\-005056a6c176})) | (@Id:{c0eeeccb\-8979\-ed11\-811f\-005056a6c176})) | (@Id:{e1c49376\-8c79\-ed11\-811f\-005056a6c176})) | (@Id:{a9cab38f\-9079\-ed11\-811f\-005056a6c176})) | (@Id:{5021db20\-9179\-ed11\-811f\-005056a6c176})) | (@Id:{e1c099fd\-9479\-ed11\-811f\-005056a6c176})) | (@Id:{f4042357\-9979\-ed11\-811f\-005056a6c176})) | (@Id:{5eb09654\-9a79\-ed11\-811f\-005056a6c176})) | (@Id:{b1221674\-267a\-ed11\-811f\-005056a6c176})) | (@Id:{f161e8f8\-2c7a\-ed11\-811f\-005056a6c176})) | (@Id:{bbe92875\-2e7a\-ed11\-811f\-005056a6c176})) | (@Id:{c45a16a1\-2f7a\-ed11\-811f\-005056a6c176})) | (@Id:{3907d3d1\-307a\-ed11\-811f\-005056a6c176})) | (@Id:{28a8d371\-307a\-ed11\-811f\-005056a6c176})) | (@Id:{b03995cc\-337a\-ed11\-811f\-005056a6c176})) | (@Id:{2b28c834\-347a\-ed11\-811f\-005056a6c176})) | (@Id:{91b0097c\-367a\-ed11\-811f\-005056a6c176})) | (@Id:{9d0adda2\-367a\-ed11\-811f\-005056a6c176})) | (@Id:{a997d162\-387a\-ed11\-811f\-005056a6c176})) | (@Id:{2518619e\-3c7a\-ed11\-811f\-005056a6c176})) | (@Id:{e7df87b4\-3f7a\-ed11\-811f\-005056a6c176})) | (@Id:{052e6a24\-437a\-ed11\-811f\-005056a6c176})) | (@Id:{cac778fe\-437a\-ed11\-811f\-005056a6c176})) | (@Id:{18176520\-447a\-ed11\-811f\-005056a6c176})) | (@Id:{84d481d1\-447a\-ed11\-811f\-005056a6c176})) | (@Id:{c6e072d8\-447a\-ed11\-811f\-005056a6c176})) | (@Id:{a1786164\-457a\-ed11\-811f\-005056a6c176})) | (@Id:{5f8ce3e9\-507a\-ed11\-811f\-005056a6c176})) | (@Id:{656840de\-517a\-ed11\-811f\-005056a6c176})) | (@Id:{7ab246df\-527a\-ed11\-811f\-005056a6c176})) | (@Id:{be2de6d4\-587a\-ed11\-811f\-005056a6c176})) | (@Id:{f1458cba\-5c7a\-ed11\-811f\-005056a6c176})) | (@Id:{a41b295b\-607a\-ed11\-811f\-005056a6c176})) | (@Id:{7998049c\-e87a\-ed11\-811f\-005056a6c176})) | (@Id:{181e3db7\-e87a\-ed11\-811f\-005056a6c176})) | (@Id:{00a74ae2\-ed7a\-ed11\-811f\-005056a6c176})) | (@Id:{dfe9bdef\-ef7a\-ed11\-811f\-005056a6c176})) | (@Id:{371d91e1\-f17a\-ed11\-811f\-005056a6c176})) | (@Id:{bbb70566\-f47a\-ed11\-811f\-005056a6c176})) | (@Id:{827bee87\-f57a\-ed11\-811f\-005056a6c176})) | (@Id:{191e679c\-f57a\-ed11\-811f\-005056a6c176})) | (@Id:{c95c8bb3\-fa7a\-ed11\-811f\-005056a6c176})) | (@Id:{ef2b2b16\-fc7a\-ed11\-811f\-005056a6c176})) | (@Id:{a8a0c0bb\-fd7a\-ed11\-811f\-005056a6c176})) | (@Id:{107e6ee3\-007b\-ed11\-811f\-005056a6c176})) | (@Id:{4910040c\-247b\-ed11\-811f\-005056a6c176})) | (@Id:{9fee833c\-257b\-ed11\-811f\-005056a6c176})) | (@Id:{0a409c18\-347b\-ed11\-811f\-005056a6c176})) | (@Id:{4d46488f\-447b\-ed11\-811f\-005056a6c176})) | (@Id:{a2e8a8ea\-fdcf\-ec11\-8105\-005056a63161})) | (@Id:{1283b917\-af7b\-ed11\-811f\-005056a6c176})) | (@Id:{2a313abb\-c07b\-ed11\-811f\-005056a6c176})) | (@Id:{fcb10eae\-ce7b\-ed11\-811f\-005056a6c176})) | (@Id:{6a8061dc\-cf7b\-ed11\-811f\-005056a6c176})) | (@Id:{f1eaf912\-d17b\-ed11\-811f\-005056a6c176})) | (@Id:{7d04d14b\-d27b\-ed11\-811f\-005056a6c176})) | (@Id:{9a964340\-e57b\-ed11\-811f\-005056a6c176})) | (@Id:{8d0f6377\-e97b\-ed11\-811f\-005056a6c176})) | (@Id:{c8c08f34\-eb7b\-ed11\-811f\-005056a6c176})) | (@Id:{7335b565\-f67b\-ed11\-811f\-005056a6c176})) | (@Id:{73da4ab7\-f77b\-ed11\-811f\-005056a6c176})) | (@Id:{22510f8d\-037c\-ed11\-811f\-005056a6c176})) | (@Id:{4ba278ae\-047c\-ed11\-811f\-005056a6c176})) | (@Id:{0052ff1a\-067c\-ed11\-811f\-005056a6c176})) | (@Id:{854b6aa6\-6be0\-ec11\-8105\-005056a63161})) LIMIT 0 100
       ---> StackExchange.Redis.RedisServerException: Syntax error at offset 1100 near e4865202\-d377\-ed11\-811f\-005056a6c176
         at Redis.OM.RedisConnection.ExecuteAsync(String command, String[] args) in C:\..\RedisConnection.cs:line 52
         --- End of inner exception stack trace ---
         at Redis.OM.RedisConnection.ExecuteAsync(String command, String[] args) in C:\..\RedisConnection.cs:line 52
         at Redis.OM.RediSearchCommands.SearchAsync[T](IRedisConnection connection, RedisQuery query) in C:\..\RediSearchCommands.cs:line 42
         at Redis.OM.Searching.RedisCollectionEnumerator`1.GetNextChunkAsync() in C:\..\Searching\RedisCollectionEnumerator.cs:line 178
         at Redis.OM.Searching.RedisCollectionEnumerator`1.MoveNextAsync() in C:\..\Searching\RedisCollectionEnumerator.cs:line 127
         at Redis.OM.Searching.RedisCollection`1.ToListAsync() in C:\..\Searching\RedisCollection.cs:line 214
         at Redis.OM.Searching.RedisCollection`1.ToListAsync() in C:\..\Searching\RedisCollection.cs:line 214
         at A.B.Services.Cache.GroupCacheService.GetAsync(Expression`1 predicate) in C:\..\Services\Cache\GroupCacheService.cs:line 131
         at A.B.Services.GroupService.GetGroupsAsync(String upn, IEnumerable`1 groupMember) in C:\..\Services\GroupService.cs:line 83
         at A.B.Services.GroupService.GetGroupByAsync(String upn, CancellationToken cancellationToken) in C:\..\Services\GroupService.cs:line 62
         at A.B.Controllers.GroupController.Get(CancellationToken cancellationToken) in C:\..\Controllers\GroupController.cs:line 39
         at lambda_method868(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

```

**Comment by slorello89** [comment]
Hmm, this might be an expression depth issue - probably something in RediSearch itself.
