### ISSUE TITLE
Bug with wrong decimal separator

### ISSUE THREAD

**Issue by AlexPulsesAi** [redis/redis-om-dotnet#290]
I have very simple model:
```
[Document(StorageType = StorageType.Hash, Prefixes = new[] { nameof(TestModel) })]
public class TestModel
{
    [Indexed]
    [RedisIdField]
    public Guid Id { get; set; }

    // other string properties

    public decimal SessionIndex { get; set; }
}
```

I have a char `,` in my `Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator`.

I can save data to Redis without nay issues. But this data will be saved with my comma separator.
And when I try to read the same model I have an exception:
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. ('5' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 0 | BytePositionInLine: 386.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Test.CachePOC.Test.Integration.BaseTest.Configure() in D:\Projects\Test\CachePOC\Test.CachePOC\Test.CachePOC.Test.Integration\BaseTest.cs:line 66

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
JsonException: '5' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 0 | BytePositionInLine: 386.

Inner Exception 2:
JsonReaderException: '5' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 386.
```

It seems when **Redis.OM** serialize/deserialize values then need to use `InvariantCulture`.

It is possible to provide what Culture need to use inside the **Redis.OM** library?

**Comment by slorello89** [comment]
@AlexPulsesAi - do you have the same issue if you change the storage type to `JSON`? (we've had these issues with geo, think we might have fixed them there.)

**Comment by AlexPulsesAi** [comment]
Thanks! It works fine with JSON storage type.
