### ISSUE TITLE
Error during searching by nullable Enums

### ISSUE THREAD

**Issue by AlexanderAnatolich** [redis/redis-om-dotnet#309]
It throws the error when trying to search by a nullable enum.
If I will make the enum as Not Nullable, everything works well.

Reproducing frequency 100%.

Steps for reproducing:

Use redis stack in docker.
Use the latest Redis.OM (0.4.1) with .Net 7
Create a model like that:
```
public enum SomeStatus
    {
        Unknown = -1,
        Closed = 2,
        Canceled = 3,
    }
    
[Document(IndexName = "SomeModel", Prefixes = new[] { "SomeModel" }, StorageType = StorageType.Json)]
    public class SomeModel
    {
        [RedisIdField]
        [Indexed(Aggregatable = true, Sortable = true)]
        public long Id { get; set; }

        [Indexed(Aggregatable = true, Sortable = true)]
        public long? Timestamp { get; set; }

        [Indexed]
        public DateTime EventDate { get; set; }
        
        .....
        
        [Indexed]
        public SomeStatus? SomeStatusId { get; set; }
}
```
Insert 1+ entities in redis.

Try to search by enum field.
Code example:

```
var result = redisCollection.Where(it => it.SomeStatusId == SomeStatus.Closed).ToList();
```

Error:
Type provided must be an Enum. (Parameter 'enumType')

SerializationStackTraceString:

   at System.Enum.ValidateRuntimeType(Type enumType)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan'1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at Redis.OM.Common.ExpressionTranslator.TranslateBinaryExpression(BinaryExpression binExpression)
   at Redis.OM.Common.ExpressionTranslator.BuildQueryFromExpression(Expression expression, Type type, Expression mainBooleanExpression)
   at Redis.OM.Searching.RedisCollectionEnumerator`1..ctor(Expression exp, IRedisConnection connection, Int32 chunkSize, RedisCollectionStateManager stateManager, Expression`1 booleanExpression, Boolean saveState)
   at Redis.OM.Searching.RedisCollection`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   
StackTrace:
   
at System.Enum.ValidateRuntimeType(Type enumType) in /_/src/libraries/System.Private.CoreLib/src/System/Enum.cs:line 1392
   at System.Enum.TryParse(Type enumType, ReadOnlySpan'1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result) in /_/src/libraries/System.Private.CoreLib/src/System/Enum.cs:line 560
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result) in /_/src/libraries/System.Private.CoreLib/src/System/Enum.cs:line 494
   at Redis.OM.Common.ExpressionTranslator.TranslateBinaryExpression(BinaryExpression binExpression)
   at Redis.OM.Common.ExpressionTranslator.BuildQueryFromExpression(Expression expression, Type type, Expression mainBooleanExpression)
   at Redis.OM.Searching.RedisCollectionEnumerator`1..ctor(Expression exp, IRedisConnection connection, Int32 chunkSize, RedisCollectionStateManager stateManager, Expression`1 booleanExpression, Boolean saveState)
   at Redis.OM.Searching.RedisCollection`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs:line 83
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) in /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs:line 29

**Comment by slorello89** [comment]
Looks like we're not pulling the underlying type out from enums when building the queries - opened PR to address.

**Comment by AlexanderAnatolich** [comment]
@slorello89 Ty, for the your work and quick feedback)
When we can expect the new release of the NuGet package?)
