### ISSUE TITLE
AggregationSet with logical operator exception: Invalid Expression Type

### ISSUE THREAD

**Issue by giabos** [redis/redis-om-dotnet#353]
Hello,
I'm getting a "System.ArgumentException : **Invalid Expression Type**" when trying to combine logical operators in AggregationSet where clause.

here is an example app to reproduce the issue: 

`
using` System.Linq.Expressions;
using Redis.OM;
using Redis.OM.Aggregation;
using Redis.OM.Modeling;

var provider = new RedisConnectionProvider("redis://localhost:6379");

// OK 
var caiColl = provider.RedisCollection<Model>();
Expression<Func<Model, bool>> query1 = a => a.Id == 0 && (a.StatusId == 2 || a.StatusId == 50);
var list = caiColl.Where(query1).ToList();

// KO (with
var caiAggr = provider.AggregationSet<Model>();
Expression<Func<AggregationResult<Model>, bool>> query = a => a.RecordShell!.Id == 0 && (a.RecordShell!.StatusId == 2 || a.RecordShell!.StatusId == 50);
var counts = caiAggr.Where(query).GroupBy(a => a.RecordShell!.Color).CountGroupMembers().ToArray();

[Document(StorageType = StorageType.Hash, Prefixes = new[] { "bug" }, IndexName = "idxCachedAuctionItem")]
class Model
{
        [RedisIdField]
        [Indexed]
        public long Id { get; set; }
        [Indexed]
        public int StatusId { get; set; }
        [Searchable(Sortable = true)]
        public string Color { get; set; } = "";
}
`

Exception thrown:

`
An unhandled exception of type 'System.ArgumentException' occurred in Redis.OM.dll: 'Invalid Expression Type'
   at Redis.OM.Aggregation.AggregationPredicates.QueryPredicate.ValidateAndPushOperand(Expression expression, Stack`1 stack)
   at Redis.OM.Common.BooleanExpression.SplitExpression()
   at Redis.OM.Aggregation.AggregationPredicates.QueryPredicate.Serialize()
   at Redis.OM.Aggregation.RedisAggregation.Serialize()
   at Redis.OM.Aggregation.AggregationEnumerator`1.get_SerializedArgs()
   at Redis.OM.Aggregation.AggregationEnumerator`1.StartEnumeration()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in C:\temp\bug-redis-om\Program.cs:line 16
`

Thanks for the help!

Kind regards,
Giovanni.

**Comment by slorello89** [comment]
hmmm definitely something that should work - could be how it's parsing the expressions - will look into it.
