### ISSUE TITLE
RedisCollection with logical operator exception: Invalid Cast Exception

### ISSUE THREAD

**Issue by nuadolos** [redis/redis-om-dotnet#359]
Hello,
I get a `System.InvalidCastException` exception when I want to query two Contains methods with negation.

My working example of a .net 6 console application to reproduce the problem:
```
using Redis.OM.Modeling;
using Redis.OM;
using System.Linq.Expressions;

var provider = new RedisConnectionProvider("redis://127.0.0.1:6379");
provider.Connection.DropIndexAndAssociatedRecords(typeof(Model));
await provider.Connection.CreateIndexAsync(typeof(Model));

var modelCollection = provider.RedisCollection<Model>();
await modelCollection.InsertAsync(new[]
{
    new Model {
        Id = 1,
        FirstName = "Andrey",
        LastName = "Bred"
    },
    new Model {
        Id = 2,
        FirstName = "Andrey",
        LastName = "Test"
    }
});

// OK 
Expression<Func<Model, bool>> whereExpressionOk1 = a => a.FirstName.Contains("Andrey") && a.LastName.Contains("Bred");
var listOk1 = await modelCollection
    .Where(whereExpressionOk1)
    .ToListAsync();

// OK
Expression<Func<Model, bool>> whereExpressionOk2 = a => a.FirstName.Contains("Andrey") && !a.LastName.Contains("Bred");
var listOk2 = await modelCollection
    .Where(whereExpressionOk2)
    .ToListAsync();

// OK
Expression<Func<Model, bool>> whereExpressionOk3 = a => a.Id != 0 && !a.FirstName.Contains("Andrey") && !a.LastName.Contains("Bred");
var listOk3 = await modelCollection
    .Where(whereExpressionOk3)
    .ToListAsync();

// Fail (System.InvalidCastException: 'Unable to cast object of type 'System.Linq.Expressions.InstanceMethodCallExpression1' to type 'System.Linq.Expressions.MemberExpression'.')
Expression<Func<Model, bool>> whereExpressionFail1 = a => !a.FirstName.Contains("Andrey") && !a.LastName.Contains("Bred");
var listFail1 = await modelCollection
    .Where(whereExpressionFail1)
    .ToListAsync();

[Document(StorageType = StorageType.Hash, Prefixes = new[] { "bug" }, IndexName = "bug-idx")]
class Model
{
    [RedisIdField]
    [Indexed]
    public long Id { get; set; }

    [Searchable]
    public string FirstName { get; set; } = null!;

    [Searchable]
    public string LastName { get; set; } = null!;
}
```
Exception thrown:
```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.InstanceMethodCallExpression1' to type 'System.Linq.Expressions.MemberExpression'.
   at Redis.OM.Common.ExpressionTranslator.TranslateBinaryExpression(BinaryExpression binExpression)
   at Redis.OM.Common.ExpressionTranslator.BuildQueryFromExpression(Expression expression, Type type, Expression mainBooleanExpression)
   at Redis.OM.Searching.RedisCollectionEnumerator`1..ctor(Expression exp, IRedisConnection connection, Int32 chunkSize, RedisCollectionStateManager stateManager, Expression`1 booleanExpression, Boolean saveState)
   at Redis.OM.Searching.RedisCollection`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Redis.OM.Searching.RedisCollection`1.ToListAsync()
   at Program.<Main>$(String[] args) in C:\temp\source\repos\RedisOMTest\RedisOMTest\Program.cs:line 43
   at Program.<Main>(String[] args)
```
Thanks for the help!

**Comment by imansafari1991** [comment]
I am curious to know if it is a bug or not. But try to change your `where` like this:
`Expression<Func<Model, bool>> whereExpressionFail1 = a => !(a.FirstName.Contains("Andrey") && a.LastName.Contains("Bred"));`
I've tried this, and it worked.

**Comment by nuadolos** [comment]
Thanks for the quick reply)
Your solution really works.
But there is another problematic case that gives the same error.
```
Expression<Func<Model, bool>> whereExpressionFail1 = a => !a.FirstName.Contains("Andrey") && a.LastName.Contains("Bred");
```
I noticed a pattern that if a predicate with negation is first, it catches this exception.
I'm just building a dynamic expression and would like to find an optimal solution to this problem.

**Comment by slorello89** [comment]
Looks like it's an issue with how negations are being handled with MethodCallExpressions, fixing in #364
