### ISSUE TITLE
Time out at first redis search  (Timeout performing UNKNOWN (1000ms))

### ISSUE THREAD

**Issue by gchadid** [redis/redis-om-dotnet#362]
Hi

Using the Redis.OM to get a JSON for  the enterprise redis we get following time out (60 /1000 of the times) 

 Timeout performing UNKNOWN (1000ms), next: FT.SEARCH, inst: 2, qu: 0, qs: 1, aw: False, bw: Inactive, rs: ReadAsync, ws: Idle, in: 181, in-pipe: 0, out-pipe: 0, last-in: 2, cur-in: 2570, serverEndpoint: redis-*****.******.us-east1-mz.gcp.cloud.rlrcp.com:18600, mc: 1/1/0, mgr: 10 of 10 available, clientName: master-data-api-7ff46c85f8-fs64r(SE.Redis-v2.6.80.25426), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=32765,Min=1,Max=32767), POOL: (Threads=4,QueuedItems=2,CompletedItems=12349), v: 2.6.80.25426 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

  at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1895
         at Redis.OM.RedisConnection.Execute(String command, String[] args)
         at Redis.OM.Searching.RedisQueryProvider.ExecuteQuery[T](Expression expression, Expression mainBooleanExpression)
         at Redis.OM.Searching.RedisQueryProvider.FirstOrDefault[TResult](Expression expression)

any clue about what operation is causing the problem?

**Comment by slorello89** [comment]
Looks like it's probably an FT.SEARCH, the UNKNOWN next FT.SEARCH is something of a misnomer here - the UNKNOWN is being logged from the command Enum in stackexchange.redis.

Are you running many searches concurrently?
How large are you setting the chunk size on the collection?
How large are the documents you are pulling back?

**Comment by slorello89** [comment]
Closing this to tidy up - feel free to reopen if necessary :)
