### ISSUE TITLE
Searching in string which contains json throws an exception

### ISSUE THREAD

**Issue by goodstas** [redis/redis-om-dotnet#432]
Hi, i have a .net application where i use Redis Stack to store data.
Each business logic object is stored inside wrapper object as json. Wrapper object has  JsonValue property.
This is a definition of the wrapper: 
` [Document(StorageType = StorageType.Json, Prefixes = new string[] { nameof(REWrapperObject) }, IndexName = $"{nameof(REWrapperObject)}-idx")]
 public class REWrapperObject
 {
     [RedisIdField, Indexed]
     public string REUniqueId { get; set; }

     [Searchable]
     public string ObjectType { get; set; }

     [Searchable]
     public string ObjectId   { get; set; }

     [Searchable]
     public string JsonValue { get; set; }

     [Indexed(Aggregatable = true, Sortable = true)]
     public long TimeStamp { get; set; }
 }` 

Class Person definition is as follows : 
`public class Person
{      
    public Guid Id { get; set; }
          
    public string FirstName { get; set; }

    public string LastName { get; set; }

    public double Height { get; set; }
  
    public double Weight { get; set; }
  
    public DateTime Birthdate { get; set; }
}`

I use JsonSerializer from System.Text.Json and the serialization Person instance looks like that :
"{"Id":"869fa3d7-7470-4215-bfd5-cc8b8d635fc4","FirstName":"Michael","LastName":"Johnson","Height":170,"Weight":95.07,"Birthdate":"1996-08-22T00:00:00"}"

When i tried to make query which looks for substring inside JsonValue property i got an exception  
This is how query looks : `var michaels = _redisProvider.RedisCollection<REWrapperObject>().Where(obj => obj.JsonValue.Contains("\"FirstName\":\"Michael\"")).ToList();`

The exception is " Syntax error at offset 23 near FirstName
Failed on FT.SEARCH REWrapperObject1KBenchmark-idx (@JsonValue:"FirstName":"Michael") LIMIT 0 100"

By doing some elimination what can cause an error, i found out that there is a problem to look for ':' character inside JsonValue.
Even if i look only for this character. It throws the same exception just offset is different.

I will really appreciate your help to understand where is a problem.
Thank you.
@slorello89

**Comment by goodstas** [comment]
Thank you for comment @slorello89 .
I use JsonValue inside wrapper object because i want some generic solution for storing business logic objects. I can't put Person as is as a member of wrapper object because i also have Dog, Cat and etc...
With regular string this search will work but as you said Redis looks different on JsonValue with Searchable property....

I changed the attribute Searchable above JsonValue to Indexed one as you suggested and now Contains works fine.

I just want to understand if the performance of applying Indexed attribute instead of Searchable is  worse? 

What i try to check that specific property like FirstName has specific value like Michael. 
Is there a better way to do it if i want to use generic wrapper to store my objects? 

Another reason why I need wrapper because there are types which require special JsonSerializationOptions and current version of Redis.OM doesn't provide the access or possibility to provide my custom JsonSerializarionOptions.
So the solution that i found is to serialize it by myself and store it as string in the wrapper object .

**Comment by slorello89** [comment]
So I will say that the Indexed is generally more efficient (you are doing an infix check so that might be somewhat less efficient than your standard tag search)

RE sizes, 100 is the default "Chunk Size" available in the constructor, if your result set is larger than that, it will automatically paginate for you until it it pulls back the entire result set, but you are generally better off with a larger chunk size in that case. The idea is the preven very large blocking queries to Redis.

You can Adjust the Chunk size in the constructor for the Redis Collection.

**Comment by goodstas** [comment]
Thank you for the response.
Another issue that i need your help. I added array property to my wrapper object :
```
   [Indexed]
   public string[] Filters { get; set; } 
```
when i perform query like : 
`var redisObjects = wrappers.Where(_ => _.Filters[0] == "3").ToList();`
i got System.ArgumentExeption("Unknown separator type")

This is call stack : 
`   at Redis.OM.Common.ExpressionTranslator.SplitPredicateSeporators(ExpressionType type)
   at Redis.OM.Common.ExpressionTranslator.TranslateBinaryExpression(BinaryExpression binExpression)
   at Redis.OM.Common.ExpressionTranslator.BuildQueryFromExpression(Expression exp)
   at Redis.OM.Common.ExpressionTranslator.TranslateWhereMethod(MethodCallExpression expression)
   at Redis.OM.Common.ExpressionTranslator.BuildQueryFromExpression(Expression expression, Type type, Expression mainBooleanExpression, Type rootType)
   at Redis.OM.Searching.RedisCollectionEnumerator`1..ctor(Expression exp, IRedisConnection connection, Int32 chunkSize, RedisCollectionStateManager stateManager, Expression`1 booleanExpression, Boolean saveState, Type rootType, Type type)
   at Redis.OM.Searching.RedisCollection`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in ConsoleGeometryRedis\Program.cs:line 78`

What do i miss , @slorello89 ?
Thanks again.

**Comment by slorello89** [comment]
RediSearch doesn't support these sorts of equality operations (comparing a specific value within a list/array). Which is why when it tries to parse the query it blows up.

**Comment by goodstas** [comment]
Ok, i understand. From other side i entered another problem by building multiple where conditions for querying Redis.
If i have array of string which i want to use it as a filters of the query like this :
`
 for (int i = 0; i < filters.Length; ++i)
 {
     query = query.Where(obj => obj.Filters.Contains(filters[i]));
 }
` 
I got an exception when Redis.OM parses these where conditions when i call `var fetchedObjects = query.ToList();` 
The issue here is to get value from array by using index.

When i use different approach with foreach loop to build where conditions then everything works fine.
`
 foreach (var filter in filters)
 {
     query = query.Where(obj => obj.Filters.Contains(filter));
 }`

@slorello89 ,  don't you think that i should be able to access array items using index in the for loop as well as i do it with foreach loop?
