### ISSUE TITLE
Using the plugin is hampered by insufficient documentation

### ISSUE THREAD

**Issue by EarlJester** [redis/redis-om-dotnet#466]
Hello gentlemen! I've been struggling for a week now with simply launching CRUD for a model. But it turns out that the model and Expressions have collected all possible restrictions, which are not even mentioned in the documentation.

1) Lists. They can be used, but any more or less complex search produces errors, or simply returns an empty object.
_collection.Where(x => x.ScopeAsGuids.Any(a => a == uuid.Value)).ToList();
2) Special characters. Limitations of the RedisSearch plugin do not allow saving many Escape characters that may be in objects. Expresions Utilits seem to have mechanisms for how to clean them, but the mechanism of operation is fundamentally unclear.
3) Guid. In continuation of point 2, it is absolutely not clear how to work with this type and search for objects by GUID.

Here is just simple model case:
```
[Document(IdGenerationStrategyName = "Uuid4IdGenerationStrategy")]
public class CurrentMeasurement
{
    [RedisIdField]
    [Indexed]
    public Guid Id { get; set; }
    
    [Searchable]
    public required List<string> ScopeAsGuids { get; set; }
    //public required List<Guid> ScopeAsGuids { get; set; }
    
    [Searchable]
    public required string ScopeAsNames { get; set; }
    
    [Indexed]
    public double? Value { get; set; }
    
    [Indexed]
    public DateTime Time { get; set; }
}

        //System.ArgumentException: Unrecognized Expression type
        //Couse of a List
        foreach (var uuid in request.Values)
        {
            var item = _collection.Where(x => x.ScopeAsGuids.Any(a => a == uuid.Value)).ToList();

            items.Measurements_.Add(item.Adapt<Measurement>());
        }

        //System.Exception: Syntax error at offset 29 near ccc
        //Failed on FT.SEARCH currentmeasurement-idx (@ScopeAsNames:"246443b8-0ccc-d87d-2655-8444eb914df6")
        //Couse "-" in GUID
        foreach (var uuid in request.Values)
        {
            var item =_collection.Where(x => x.ScopeAsNames == uuid.Value);

            items.Measurements_.Add(item.Adapt<Measurement>());
        }

        //Working
        foreach (var uuid in request.Values)
        {
            var item = await _collection.FindById(uuid.Adapt<Guid>().ToString());

            items.Measurements_.Add(item.Adapt<Measurement>());
        }

        //Working
        foreach (var uuid in request.Values)
        {
            var item = await_collection.Where(x => x.Value == 55);

            items.Measurements_.Add(item.Adapt<Measurement>());
        }

        //No error and no data.
        //Seems like .Contain not working with search
        foreach (var uuid in request.Values)
        {
            var item = _collection.Where(x => x.ScopeAsNames.Contains(uuid.Value));

            items.Measurements_.Add(item.Adapt<Measurement>());
        }
```
Sample of object:
![image](https://github.com/user-attachments/assets/08cb8e5b-8e6f-4566-aab5-71392af15002)

For now, i see that is real documentation is -- Issues. But I don't think it should be like that))

**Comment by slorello89** [comment]
Hi @EarlJester, I think there's some misunderstanding about the [difference between](https://redis.io/learn/develop/dotnet/redis-om-dotnet/searching/creating-an-index#indexed-fields) a `Searchable` field and an `Indexed` field.

`Indexed` = anything you are expecting to exactly match against
`Searchable` = something you want to run a full text search against

You can't run a full text search against a GUID, the `-` actually tokenize the guid into several parts, so I suppose you could serach for the individual parts, but that kind of breaks the point of searching for a GUID. So The first thing you should do is change:

```cs
    [Searchable]
    public required List<Guid> ScopeAsGuids { get; set; }
```

to

```cs
    [Indexed]
    public required List<Guid> ScopeAsGuids { get; set; }
```

then your first query can just be something like:

```cs
var first = measurements.FirstOrDefault(x => x.ScopeAsGuids.Contains(guid));
```

with that second query:

```cs
    [Searchable]
    public required string ScopeAsNames { get; set; }
```

assuming you are just storing one GUID in there, you can just change the `Searchable` to `Indexed` and it should just work as:

```cs
var first = measurements.FirstOrDefault(x => x.ScopeAsNames == value);
```

If you are storing multiple GUIDs in there, that gets a lot more complicated, I would just recommend using a list of GUIDs

**Comment by EarlJester** [comment]
Thanks for the detailed answer!
The main question was that it would be necessary to make more detailed documentation so that you don’t need to answer so much in Issues)))
I tried your ideas with an example, but Redis.OM refuses to work with List<Guid>
![image](https://github.com/user-attachments/assets/449b1917-8ba9-4282-8065-f6b4a5029754)
```
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.Guid]' to type 'System.Collections.Generic.IEnumerable`1[System.Object]'.
   at Redis.OM.RedisObjectHandler.BuildHashSet(Object obj)
   at Redis.OM.RedisCommands.SetAsync(IRedisConnection connection, Object obj)
   at Redis.OM.Searching.RedisCollection`1.InsertAsync(T item)```
   
   ```[Document(IdGenerationStrategyName = "Uuid4IdGenerationStrategy")]
public class CurrentMeasurement
{
    [RedisIdField]
    [Indexed]
    public Guid Id { get; set; }
    
    [Indexed]
    public required List<Guid> ScopeAsGuids { get; set; }
    
    [Indexed]
    public required string ScopeAsNames { get; set; }
    
    [Indexed]
    public double? Value { get; set; }
    
    [Indexed]
    public DateTime Time { get; set; }
}

```

**Comment by slorello89** [comment]
@EarlJester - change the storage type to JSON rather than a hash.

**Comment by EarlJester** [comment]
@slorello89 -- thx, now all working. What issues or benefits of use Json documents?

**Comment by slorello89** [comment]
If you need any complex data types stored or any collections, JSON is the way to go, because the semantics of doing so in a hash document is very painful, and not setup to work in all circumstances as you can see.

**Comment by EarlJester** [comment]
Then maybe a good idea would be to use Json, and the RedisJson module by default))
Everyone installs redis\redis-stack anyway, which contains Search and Json.
I'll go play with JsonPath some more. Thanks and have a nice weekend!
